### ISSUE TITLE
Flutter 3.0.0 | Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.

### ISSUE THREAD

**Issue by Solano-Furlan** [idootop/custom_nested_scroll_view#1]
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../fvm/versions/3.0.0/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
Restarted application in 3,635ms.
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ #0   AuthGuard.onNavigation (package:fullpass/routes/auth_guard.dart:15:14)<…>
flutter: \^[[38;5;12m│ #1   StackRouter._canNavigate (package:auto_route/src/router/controller/routing_controller.dart:1093:13)<…>
flutter: \^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 AuthAuthorizedState()<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>

**Comment by idootop** [comment]
Thank you for your feedback. Fixed at f77fdbfa75bd2b18a882425e1d9692468ba09efb.

```yaml
# pubspec.yaml
dependencies:
  # ...
  custom_nested_scroll_view:
    git:
      url: https://github.com/idootop/custom_nested_scroll_view.git
      ref: f77fdbfa75bd2b18a882425e1d9692468ba09efb
```
