### ISSUE TITLE
breaking changes in flutter 3.4

### ISSUE THREAD

**Issue by Klabauterman** [idootop/custom_nested_scroll_view#3]
There are some breaking changes in the API of flutter 3.4:

1. `ScrollActivityDelegate` has a new method `updateBallisticAnimation` which must be implemented
2. `BallisticScrollActivity` has a new parameter in its constructor: `shouldIgnorePointer`

Has someone already looked into this?

**Comment by idootop** [comment]
Thanks for the feedback, I will update it later.

**Comment by idootop** [comment]
> There are some breaking changes in the API of flutter 3.4:
> 
>     1. `ScrollActivityDelegate` has a new method `updateBallisticAnimation` which must be implemented
> 
>     2. `BallisticScrollActivity` has a new parameter in its constructor: `shouldIgnorePointer`
> 
> 
> Has someone already looked into this?

Fixed, just need to specify the correct branch

|    Git branch   | Supported flutter versions |
|---------------|--------------------------|
| main            | >=3.4.0-27.0.pre          |
| flutter-3.4-pre | >=3.4.0-17.0.pre <3.4.0-27.0.pre |
| flutter-3.0     | >=2.12.0-4.0.pre <3.4.0-17.0.pre |
| flutter-2.x     | <2.12.0-4.0.pre           |

```yaml
dependencies:
  ...
  custom_nested_scroll_view:
    git:
      url: https://github.com/idootop/custom_nested_scroll_view.git
      # Which branch to use is based on your local flutter version
      ref: flutter-3.4-pre # flutter-2.x flutter-3.0 flutter-3.4-pre
```
